### PR TITLE
Added a Night Mode Toggle Button #35

### PR DESCRIPTION
**Pull request by Rawan1998**

### CODE REVIEW

**Comment by kumarmanish03** [comment]
Provide live link please, read https://github.com/CoffeeWithDevs/CodeWithUs/blob/main/guide.md

**Comment by Rawan1998** [comment]
Here is the live link: https://rawan1998.github.io/CodeWithUs/

**Comment by kumarmanish03** [comment]
Hey @Rawan1998, Good Work, but we still not completed
* Night toggle not working for the Contact section, fix this
* Don't make background simply black instead use   ```background-image: linear-gradient(315deg, #555 50%, #2f2f2f 50%);```

**Comment by Rawan1998** [comment]
HI @kumarmanish03 , Please check the new modifications and tell me if there is anything that needs to be changed.

**Comment by kumarmanish03** [comment]
Also,
* Fix toggle button on the navbar
* When night mode, change the color of the navbar also(don't worry about the grey color of the logo as I have a white logo also)
* Linear gradient, the color change is sharp, make it like a gradient (https://www.w3schools.com/css/css3_gradients.asp#:~:text=Gradient%20Backgrounds,Gradients%20(defined%20by%20their%20center))
* Align Contact section heading in the center

**Comment by kumarmanish03** [comment]
Any updates?

**Pull request closed without merging**
