### PR TITLE
Added Button in Showcase

### PR DESCRIPTION
**Pull request by pratyushakatti13**
Created a button with hover effect. The button opens the link in new tab.

### CODE REVIEW

**Comment by kumarmanish03** [comment]
Also, add a screenshot of your page for reviewing

**Comment by pratyushakatti13** [comment]
Initially:
Capture5


When hovered:
Capture6

Is there change in the style that I have to do?

**Comment by kumarmanish03** [comment]
Nice!!!

**Comment by kumarmanish03** [comment]
@pratyushakatti13 You may take more issues!

**Pull request merged**
