### PR TITLE
Add responsive nav-bar

### PR DESCRIPTION
**Pull request by ka-hn**
This will add responsive navigation bar. See example images below.

Fixes issue #18 

**Desktop OLD**
Desktop-Nav-Bar-Old

**Desktop NEW**
Desktop-Nav-Bar-New

**Mobile OLD**
Mobile-Nav-Bar-Old

**Mobile NEW Collapsed**
Mobile-Nav-Bar-New-Collapsed

**Mobile NEW Expanded**
Mobile-Nav-Bar-New-Expanded

### CODE REVIEW

**Comment by kumarmanish03** [comment]
@ka-hn Great Work!!! Keep contributing

**Comment by kumarmanish03** [comment]
Hey @ka-hn, when I merged your pr there are some issues with the navbar, it was not showing the hamburger icon
So I revert the changes and then some hell happens as can see on live site
Now, your task is to fix the current bug to the original one you created
PS: Resolve this as soon as possible

**Comment by ka-hn** [comment]
@kumarmanish03

I will look into it, however since it's reverted I cannot reproduce (the unresponsive one is on the live site) but I will try again and see if I can find the issue somehow

**Comment by kumarmanish03** [comment]
@ka-hn Also update your cloned repo with the remote before making any changes

**Comment by ka-hn** [comment]
@kumarmanish03 I have recreated everything now and on my side I cannot se any bug at all. Can you please explain what the bug is / was?

The Hamburger menu is supposed to appear when you are only on mobile devices. Do you want the hamburger menu to be persistent at all times?

**Comment by kumarmanish03** [comment]
No, I only want Hamburger menu for mobile devices only.
Now, make a separate PR of your changes
Also create gh-page of your forked repo for easy reviewing

**Pull request merged**
