### PR TITLE
Preloader Added

### PR DESCRIPTION
**Pull request by IC1101Virgo**
Here is the live link for the same: https://ic1101virgo.github.io/CodeWithUs/

### CODE REVIEW

**Comment by kumarmanish03** [comment]
That's gone wrong, you have to add javascript as well for showing the main content after 3-4 seconds(using setTimeout function)
You may go through this commit to see the code
https://github.com/GeekHaven/Geektoberfest-Main/pull/148/commits/9d52ab20e5378829f5f2f7f05592294e95a52cd6 
Let me know if any help required

**Comment by IC1101Virgo** [comment]
@kumarmanish03 ok on it! :)

**Comment by IC1101Virgo** [comment]
@kumarmanish03 its working fine now! :) Checkout the link :  https://ic1101virgo.github.io/CodeWithUs/

**Comment by kumarmanish03** [comment]
Nice :+1: 
Also, add yourself as contributors, read #2

**Pull request merged**
