### PR TITLE
created responsive footer

### PR DESCRIPTION
**Pull request by ritviksharma3**
@kumarmanish03 @geeks5551 Created a responsive footer for issue #6 and adding the details mentioned in issue #2. Please Review. Happy Developing ;)

### CODE REVIEW

**Comment by kumarmanish03** [comment]
Hey @ritviksharma3 Can you create a live link to your change site
If you don't know follow these steps: 
1. Go to the settings of your forked repo
2. Go to Github pages and then
Screenshot from 2020-10-26 22-15-35
in Sources column change none to main/master and then save

3. Then you able to see your live link, after a few minutes you are able to your site as well on given link
Congrats, you created your live site

**Comment by kumarmanish03** [comment]
Do let me know if you find any difficulty
Also, provide your live link

**Comment by ritviksharma3** [comment]
Hi ! I'm facing some issues hosting the website, for your reference I'm attaching a screenshot. For any changes please get back to me.
Screenshot (222)

**Comment by kumarmanish03** [comment]
You may join this WhatsApp group https://chat.whatsapp.com/FMj6QbsqlMy8Td9o2kA44g
we will surely try to resolve your query

Btw, the footer looks fine, but if you host it then it is much better for us for reviewing

**Comment by ritviksharma3** [comment]
Thank you for merging it. Happy Developing ! @kumarmanish03

**Comment by kumarmanish03** [comment]
@ritviksharma3 You may join this WhatsApp group https://chat.whatsapp.com/FMj6QbsqlMy8Td9o2kA44g
if you require any type of help and instant notification for new issues

**Pull request merged**
