### PR TITLE
Scroll up feature added

### PR DESCRIPTION
**Pull request by nusart**

### CODE REVIEW

**Comment by kumarmanish03** [comment]
Resolve your conflicts
Also, provide live link

**Comment by kumarmanish03** [comment]
Hey @Nusart  Can you create a live link
If you don't know follow these steps: 
1. Go to the settings of your forked repo
2. Go to Github pages and then
Screenshot from 2020-10-26 22-15-35
in Sources column change none to main/master and then save

3. Then you able to see your live link, after a few minutes you are able to your site as well on the given link
Congrats, you created your live site

**Comment by nusart** [comment]
Live link is ready for viewing. For conflicts, please provide me write access so that I can resolve them manually.

**Comment by kumarmanish03** [comment]
To resolve conflicts just remove >>>>>>>main from conflicting files

And also give live link as well

**Comment by nusart** [comment]
https://nusart.github.io/CodeWithUs/

**Comment by nusart** [comment]
@kumarmanish03 I dont seem to find these >>>>>>>main in any of the conflicting files. Help needed.

**Comment by kumarmanish03** [comment]
If you find any difficulties in resolving conflicts, follow these steps:
* Delete your forked repo
* Then again forked the repo and cloned that repo in your system
* Make your changes 
* Then create a pull request
And don't forget to create live link again

**Pull request closed without merging**
